[tool.poetry]
name = "behavysis_pipeline"
version = "0.1.23"
description = "An animal behaviour processing and analysis package"
authors = ["BowenLab"]
license = "LGPL-3.0-or-later"
readme = "README.md"
homepage = "https://tlee08.github.io/behavysis_pipeline"
repository = "https://github.com/tlee08/behavysis_pipeline"
documentation = "https://tlee08.github.io/behavysis_pipeline"
packages = [{ include = "behavysis_pipeline" }]

[tool.poetry.dependencies]
python = "^3.12"
behavysis_core = "^0.1.3"
behavysis_classifier = "^0.1.21"
Jinja2 = "^3.1.4"
pyqtgraph = "^0.13.7"
PySide6 = "^6.8.0.2"
dask = { extras = ["complete"], version = "^2024.10.0" }
graphviz = "^0.20.3"
# prefect = "^2.19.8"
streamlit = "^1.36.0"

[tool.poetry.group.dev.dependencies]
behavysis_core = { path = "../behavysis_core", develop = true }
behavysis_classifier = { path = "../behavysis_classifier", develop = true }
ruff = "^0.4.8"
mkdocs-material = "^9.5.18"
mkdocstrings-python = "^1.9.2"

[tool.poetry.scripts]
behavysis_make_project = "behavysis_pipeline.scripts.make_project:main"
behavysis_project_gui = "behavysis_pipeline.scripts.project_gui:run_script"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
