[tool.poetry]
name = "behavysis"
version = "0.1.24"
description = "An animal behaviour processing and analysis package"
authors = ["BowenLab"]
license = "GNU GPLv3"
readme = "README.md"
homepage = "https://tlee08.github.io/behavysis"
repository = "https://github.com/tlee08/behavysis"
documentation = "https://tlee08.github.io/behavysis"
packages = [{ include = "behavysis" }]

[tool.poetry.dependencies]
python = "~3.12"
pydantic = "^2.7.0"
numpy = "^1.26.4"
pandas = "^2.2.2"
tables = "^3.10.1"
pyarrow = "^18.0.0"
scipy = "^1.13.0"
opencv-python = "^4.9.0.80"
seaborn = "^0.13.2"
natsort = "^8.4.0"
tqdm = "^4.30.0"
Jinja2 = "^3.1.4"
# Multiprocessing
dask = { extras = ["complete"], version = "^2024.10.0" }
graphviz = "^0.20.3"
# GUI
PySide6 = "^6.8.0.2"
pyqtgraph = "^0.13.7"
streamlit = "^1.36.0"
# Classifier
scikit-learn = "^1.4.2"
# torch = "~2.6.0"
torch = { version = "~2.6.0", source = "torch" }

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.8"
mkdocs-material = "^9.5.18"
mkdocstrings-python = "^1.9.2"
pytest = "^8.3.3"

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu126"
priority = "explicit"

[tool.poetry.scripts]
behavysis_init = "behavysis.scripts.init:main"
behavysis_make_project = "behavysis.scripts.make_project:main"
behavysis_project_gui = "behavysis.scripts.project_gui:run_script"
behavysis_viewer = 'behavysis.viewer.__main__:main'

[tool.ruff]
line-length = 120

[tool.ruff.format]
docstring-code-format = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
